# Generated by Django 4.0.4 on 2022-06-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='content',
            new_name='author',
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
