# Generated by Django 4.0.4 on 2023-08-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
